// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace GlucoTrack_api.Models;

public partial class GlucoTrackDBContext : DbContext
{
    public GlucoTrackDBContext()
    {
    }

    public GlucoTrackDBContext(DbContextOptions<GlucoTrackDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TabAlert> TabAlert { get; set; }

    public virtual DbSet<TabAlertUtentiDestinatari> TabAlertUtentiDestinatari { get; set; }

    public virtual DbSet<TabAssunzioniFarmaci> TabAssunzioniFarmaci { get; set; }

    public virtual DbSet<TabComorbiditaPazienti> TabComorbiditaPazienti { get; set; }

    public virtual DbSet<TabFattoriRischio> TabFattoriRischio { get; set; }

    public virtual DbSet<TabLogModifiche> TabLogModifiche { get; set; }

    public virtual DbSet<TabMisurazioniGlicemia> TabMisurazioniGlicemia { get; set; }

    public virtual DbSet<TabPatologie> TabPatologie { get; set; }

    public virtual DbSet<TabPazientiFattoriRischio> TabPazientiFattoriRischio { get; set; }

    public virtual DbSet<TabPazientiMedici> TabPazientiMedici { get; set; }

    public virtual DbSet<TabProgrammazioneAssunzioni> TabProgrammazioneAssunzioni { get; set; }

    public virtual DbSet<TabRuoli> TabRuoli { get; set; }

    public virtual DbSet<TabSintomi> TabSintomi { get; set; }

    public virtual DbSet<TabTerapie> TabTerapie { get; set; }

    public virtual DbSet<TabTipologieAlert> TabTipologieAlert { get; set; }

    public virtual DbSet<TabTipologieMisurazioni> TabTipologieMisurazioni { get; set; }

    public virtual DbSet<TabTipologiePasti> TabTipologiePasti { get; set; }

    public virtual DbSet<TabUtenti> TabUtenti { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=127.0.0.1,1433;Initial Catalog=GlucoTrackDB;Persist Security Info=True;User ID=sa;Password=baseBase100;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TabAlert>(entity =>
        {
            entity.HasKey(e => e.IdAlert).HasName("PK__TabAlert__BCD48A589CCEE8F8");

            entity.Property(e => e.CreatoIl).HasColumnType("datetime");
            entity.Property(e => e.Messaggio)
                .IsRequired()
                .HasColumnType("text");
        });

        modelBuilder.Entity<TabAlertUtentiDestinatari>(entity =>
        {
            entity.HasKey(e => e.IdAlertUtentiDestinatari).HasName("PK__TabAlert__CE259670CAAA9013");

            entity.Property(e => e.Letto).HasDefaultValue(false);
            entity.Property(e => e.LettoIl).HasColumnType("datetime");
        });

        modelBuilder.Entity<TabAssunzioniFarmaci>(entity =>
        {
            entity.HasKey(e => e.IdAssunzioneFarmaco).HasName("PK__TabAssun__3A8E09508166E6C7");

            entity.Property(e => e.AssuntoIl).HasColumnType("datetime");
            entity.Property(e => e.NomeFarmacoAssunto)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Note).HasColumnType("text");
            entity.Property(e => e.QuantitaPrevistaValore).HasColumnType("numeric(8, 2)");
            entity.Property(e => e.UnitaMisura)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TabComorbiditaPazienti>(entity =>
        {
            entity.HasKey(e => e.IdComorbiditaPaziente).HasName("PK__TabComor__7F537BA4C7D78268");

            entity.Property(e => e.Comorbidita)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TabFattoriRischio>(entity =>
        {
            entity.HasKey(e => e.IdFattoreRischio).HasName("PK__TabFatto__8B2469FE1AD382B1");

            entity.HasIndex(e => e.Nome, "UQ__TabFatto__7D8FE3B2D49825BA").IsUnique();

            entity.Property(e => e.Descrizione).HasColumnType("text");
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TabLogModifiche>(entity =>
        {
            entity.HasKey(e => e.IdLog).HasName("PK__TabLogMo__0C54DBC6DE4D2BDF");

            entity.Property(e => e.Azione)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.TabellaNome)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Timestamp)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<TabMisurazioniGlicemia>(entity =>
        {
            entity.HasKey(e => e.IdMisurazioneGlicemia).HasName("PK__TabMisur__FFD8C29304B3D111");

            entity.Property(e => e.MisuratoIl).HasColumnType("datetime");
            entity.Property(e => e.Note).HasColumnType("text");
        });

        modelBuilder.Entity<TabPatologie>(entity =>
        {
            entity.HasKey(e => e.IdPatologia).HasName("PK__TabPatol__6D573A32E29E0018");

            entity.Property(e => e.Dal).HasColumnType("datetime");
            entity.Property(e => e.Descrizione)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TabPazientiFattoriRischio>(entity =>
        {
            entity.HasKey(e => e.IdPazienteFattoreRischio).HasName("PK__TabPazie__17D4F54DBCF0D4FA");
        });

        modelBuilder.Entity<TabPazientiMedici>(entity =>
        {
            entity.HasKey(e => e.IdPazienteMedico).HasName("PK__TabPazie__662F2A96B2608491");
        });

        modelBuilder.Entity<TabProgrammazioneAssunzioni>(entity =>
        {
            entity.HasKey(e => e.IdProgrammazione).HasName("PK__TabProgr__100315284CAA9F43");

            entity.Property(e => e.DataOraPrevista).HasColumnType("datetime");
            entity.Property(e => e.NomeFarmacoProgrammato)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.QuantitaPrevistaN).HasColumnType("numeric(8, 2)");
            entity.Property(e => e.QuantitaPrevistaUn)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TabRuoli>(entity =>
        {
            entity.HasKey(e => e.IdRuolo).HasName("PK__TabRuoli__5F37071D42BF3AA8");

            entity.HasIndex(e => e.NomeRuolo, "UQ__TabRuoli__5663F8FCAC05DAB1").IsUnique();

            entity.Property(e => e.NomeRuolo)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TabSintomi>(entity =>
        {
            entity.HasKey(e => e.IdSintomo).HasName("PK__TabSinto__FF5EADBF645624C2");

            entity.Property(e => e.AvvenutoIl).HasColumnType("datetime");
            entity.Property(e => e.Descrizione)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TabTerapie>(entity =>
        {
            entity.HasKey(e => e.IdTerapia).HasName("PK__TabTerap__EC02E57C85298A87");

            entity.Property(e => e.AggiornatoIl).HasColumnType("datetime");
            entity.Property(e => e.CreatoIl).HasColumnType("datetime");
            entity.Property(e => e.Indicazioni).HasColumnType("text");
        });

        modelBuilder.Entity<TabTipologieAlert>(entity =>
        {
            entity.HasKey(e => e.IdTipologiaAlert).HasName("PK__TabTipol__8373FF9B965E186E");

            entity.HasIndex(e => e.Codice, "UQ__TabTipol__0636EC1D87C8EF89").IsUnique();

            entity.Property(e => e.Codice)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Descrizione).HasColumnType("text");
        });

        modelBuilder.Entity<TabTipologieMisurazioni>(entity =>
        {
            entity.HasKey(e => e.IdTipologiaMisurazione).HasName("PK__TabTipol__38C9CC031024A747");

            entity.HasIndex(e => e.Nome, "UQ__TabTipol__7D8FE3B2D6683BE9").IsUnique();

            entity.Property(e => e.Descrizione).HasColumnType("text");
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TabTipologiePasti>(entity =>
        {
            entity.HasKey(e => e.IdTipologiaPasto).HasName("PK__TabTipol__58FC87BA2A00460D");

            entity.HasIndex(e => e.Nome, "UQ__TabTipol__7D8FE3B2B09CD0A4").IsUnique();

            entity.Property(e => e.Descrizione).HasColumnType("text");
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TabUtenti>(entity =>
        {
            entity.HasKey(e => e.IdUtente).HasName("PK__TabUtent__0816694B50F339F3");

            entity.HasIndex(e => e.NomeUtente, "UQ__TabUtent__599A34B49D5F8BDC").IsUnique();

            entity.HasIndex(e => e.Email, "UQ__TabUtent__A9D105346B2FFCC0").IsUnique();

            entity.Property(e => e.Altezza).HasColumnType("numeric(5, 2)");
            entity.Property(e => e.CodiceFiscale)
                .HasMaxLength(16)
                .IsUnicode(false);
            entity.Property(e => e.Cognome)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatoIl).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.HashPassword)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Nome)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.NomeUtente)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.OspedaleAffiliazione)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Peso).HasColumnType("numeric(5, 2)");
            entity.Property(e => e.Sesso).HasMaxLength(100);
            entity.Property(e => e.Specializzazione)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.UltimoAccesso).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}