// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabAlertUtentiDestinatari
{
    public int IdAlertUtentiDestinatari { get; set; }

    public int IdAlert { get; set; }

    public int IdUtenteDestinario { get; set; }

    public bool? Letto { get; set; }

    public DateTime? LettoIl { get; set; }
}