// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabAssunzioniFarmaci
{
    public int IdAssunzioneFarmaco { get; set; }

    public int IdPaziente { get; set; }

    public int? IdProgrammazione { get; set; }

    public DateTime AssuntoIl { get; set; }

    public decimal QuantitaPrevistaValore { get; set; }

    public string UnitaMisura { get; set; }

    public string Note { get; set; }
}