// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabAlert
{
    public int IdAlert { get; set; }

    public int IdTipologiaAlert { get; set; }

    public int IdPaziente { get; set; }

    public string Messaggio { get; set; }

    public DateTime? CreatoIl { get; set; }
}