// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabComorbiditaPazienti
{
    public int IdComorbiditaPaziente { get; set; }

    public int IdPaziente { get; set; }

    public string Comorbidita { get; set; }

    public DateOnly? DataInizio { get; set; }

    public DateOnly? DataFine { get; set; }
}