// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabLogModifiche
{
    public int IdLog { get; set; }

    public int IdMedico { get; set; }

    public string TabellaNome { get; set; }

    public int IdRecord { get; set; }

    public string Azione { get; set; }

    public DateTime Timestamp { get; set; }

    public string DettagliPrima { get; set; }

    public string DettagliDopo { get; set; }
}