// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabMedici
{
    public int IdMedico { get; set; }

    public int IdUtente { get; set; }

    public string Specializzazione { get; set; }

    public string OspedaleAffiliazione { get; set; }

    public string Nome { get; set; }

    public string Cognome { get; set; }
}