// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabMisurazioniGlicemia
{
    public int IdMisurazioneGlicemia { get; set; }

    public int IdUtente { get; set; }

    public DateTime MisuratoIl { get; set; }

    public int IdTipologiaMisurazione { get; set; }

    public int IdTipologiaPasto { get; set; }

    public short Valore { get; set; }

    public string Note { get; set; }
}