// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabPazienti
{
    public int IdPaziente { get; set; }

    public int IdUtente { get; set; }

    public DateOnly? DataNascita { get; set; }

    public decimal? Altezza { get; set; }

    public decimal? Peso { get; set; }

    public string CodiceFiscale { get; set; }

    public string Sesso { get; set; }
}