// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabPazientiMedici
{
    public int IdPazienteMedico { get; set; }

    public int IdPaziente { get; set; }

    public int IdMedico { get; set; }

    public DateOnly Dal { get; set; }

    public DateOnly? Al { get; set; }
}