// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabProgrammazioneAssunzioni
{
    public int IdProgrammazione { get; set; }

    public int IdTerapia { get; set; }

    public string Farmaco { get; set; }

    public decimal QuantitaPrevistaN { get; set; }

    public string QuantitaPrevistaUn { get; set; }

    public DateTime DataOraPrevista { get; set; }
}