// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabPazientiFattoriRischio
{
    public int IdPazienteFattoreRischio { get; set; }

    public int IdUtente { get; set; }

    public int IdFattoreRischio { get; set; }
}