// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabPatologie
{
    public int IdPatologia { get; set; }

    public int IdPaziente { get; set; }

    public string Descrizione { get; set; }

    public DateTime? Dal { get; set; }
}