// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabRuoli
{
    public int IdRuolo { get; set; }

    public string NomeRuolo { get; set; }
}