// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabSintomi
{
    public int IdSintomo { get; set; }

    public int IdUtente { get; set; }

    public string Descrizione { get; set; }

    public DateTime AvvenutoIl { get; set; }
}