// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabTerapie
{
    public int IdTerapia { get; set; }

    public int IdMedico { get; set; }

    public int IdPaziente { get; set; }

    public string Indicazioni { get; set; }

    public DateOnly? DataInizio { get; set; }

    public DateOnly? DataFine { get; set; }

    public DateTime? CreatoIl { get; set; }

    public DateTime? AggiornatoIl { get; set; }
}