// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabTipologieAlert
{
    public int IdTipologiaAlert { get; set; }

    public string Codice { get; set; }

    public string Descrizione { get; set; }
}