// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlucoTrack_api.Models;

public partial class TabUtenti
{
    public int IdUtente { get; set; }

    public string NomeUtente { get; set; }

    public string HashPassword { get; set; }

    public string Nome { get; set; }

    public string Cognome { get; set; }

    public string Email { get; set; }

    public int IdRuolo { get; set; }

    public DateTime? CreatoIl { get; set; }

    public DateTime? UltimoAccesso { get; set; }
}